### ISSUE TITLE
Selección de SimCard

### ISSUE THREAD

**Issue by dariosb** [vortexmakes/AgroIoT#11]
El nuevo equipo TrackingSTM32 permite elegir la SimCard conectada al ModemGSM.
Es necesario definir:
- Cual es el Slot principal.
- En que contexto se requiere realiza el cambio de SimCard.

**Comment by truelsegaard** [comment]
El slot principal si queres tomamos el que arranca por defecto la llave, y lo que habíamos hablado con Leo del cambio de SimCard para no complicar la lógica por ahora era cambiar de sim cada vez que se corta o no se conecta y sale por timeout que en la lógica apaga el modulo para arrancar de cero, ahí aprovechar y cambiar de sim. o si les parece mejor otra forma la vemos.

**Comment by truelsegaard** [comment]
En el slot por defecto va a ir el sim que estamos usando de movistar, el otro va a ser de Claro.

**Comment by dariosb** [comment]
Ok X2 (mas cercano al SIM5320) es el por defecto.
Estoy de acuerdo con la lógica de cambio.

**Comment by dariosb** [comment]
Pendiente:
indicación de Sim actual usando sequence
