### ISSUE TITLE
Indicadores LED1-6

### ISSUE THREAD

**Issue by dariosb** [vortexmakes/AgroIoT#12]
Definir uso de cada indicador

**Comment by truelsegaard** [comment]
Escribo una base de los estados actuales con algunas sugerencias, y faltan definir algunos estados:

**Led 1 rojo:**:
Alimentacion externa / bateria / error grave ( por ejemplo sim error ).

**Led 2: GSM status:**
stage 1: cuando el modulo contesta AT
stage 2: cuando llega 'sim ready'
stage 3: cuando se registro en la red
stage 4: cuando le asignaron ip y va a abrir el socket
lit: cuando llega el ACK de la trama actual.

**Led 3: tramas en flash:**
Después de enviar la trama actual, cuando chequea la cola, si tiene tramas almacenadas lo enciende, si la cola esta vacía lo apaga.

**Led 4: GPS status:**
stage 2: sin señal gps
lit: con señal gps

**Led 5: working status**
A definir, tendríamos que mostrar el estado 'working' que puede venir por entradas o por cbox, en el equipo viejo usábamos 2 leds, acá tendríamos que usar uno solo...o redefinir otro para dejar uno libre.

**Led 6: sim** 
necesitaríamos mostrar con que sim esta conectado, ejemplo:
Stage1: Movistar
Stage2: Claro

**Comment by dariosb** [comment]
Adaptar pinout Leds
Invocar al seteo de secuencias en contexto de aplicación

**Comment by dariosb** [comment]
Se integró el módulo sequence sobre STM32 e implementó la indicación del Led 6: SIM

**Comment by dariosb** [comment]
Led2, Led4 y Led6 ya están implementados

Faltan 
**Led1:** 
El equipo no funciona por mas de una fracción de segundo alimentado solo con batería, solo se sincronizan los archivos y se apaga por lo tanto no le encuentro sentido a mostrar una indicación de funcionamiento con batería.
Propongo utilizar este led para indicar por ejemplo si hay fallas en el acceso a las memorias
Encendido fijo: No hay fallas en las memorias internas y se está guardando el backup en Pendrive
Apagado: No hay fallas en memorias y no se está guardando el backup en el Pendrive
stage 1: falla en dataflash
stage 2: dataflash requiere powercycle
stage 3: falla en eeprom

**Led3  tramas en flash:** 
Falta incluir en contexto de CommMgr la llamada a `set_led(LED_STORAGE, SEQ_LIT/SEQ_NO_LIT)`

**Led5: working status**
Falta incluir en contexto de CommMgr la llamada a `set_led(LED_WORK, SEQ_LIT/SEQ_NO_LIT)`

**Comment by leanfrancucci** [comment]
> Led3 tramas en flash

Inicio con el led apagado.
Cuando determino si hay o no historia para enviar, lo enciendo o lo dejo apagado, respectivamente.
Si lo enciendo, lo apago cuando termina de enviar la historia

Está bien?

**Comment by truelsegaard** [comment]
Si, el tema que cuando esta mapeando siempre que tira la actual tiene al menos 20 tramas almacenadas, si no las envía queda apagado, si por alguna razón se corta o no puede enviarlas que se empiezan a almacenar queda encendido.
Creo que la logica esta bien.

**Comment by leanfrancucci** [comment]
> Led 5: working status

Inicia con el led apagado.
En el estado Stopped de Mapping se mantiene apagado.
En el estado Running de Mapping se mantiene encendido.

Está bien?

**Comment by leanfrancucci** [comment]
@truelsegaard 
> Si, el tema que cuando esta mapeando siempre que tira la actual tiene al menos 20 tramas almacenadas, si no las envía queda apagado, si por alguna razón se corta o no puede enviarlas que se empiezan a almacenar queda encendido.

Puedo hacer que apague si falla en el envío de la historia

**Comment by truelsegaard** [comment]
Ese es el que tendríamos que diferenciar de donde viene el mapping, seria algo así:
comunicándose con cbox: stage1
pqty > 0 : stage2
IN1 o IN2 mapeando: stage 3
stage1 y stage2: stage4
stage 2 y stage3: lit

Es para que a campo nos deje diferenciar si se esta comunicando, si andan los sensores de la noria, si andan las entradas, etc

**Comment by truelsegaard** [comment]
Lo agregamos al archivo de SensorData del drive si queres así queda mas claro

**Comment by leanfrancucci** [comment]
> diferenciar de donde viene el mapping

Lo dejamos para cuando probemos dispositivos 485

**Comment by truelsegaard** [comment]
Dale no hay problema, IN1 y IN2 puede ser LIT cuando esta mapeando o como quieras

**Comment by leanfrancucci** [comment]
Esta es la máquina de la comunicación con el server (CommMgr)
![CommMgr](https://user-images.githubusercontent.com/33349769/86536514-9e78c500-bebe-11ea-81db-cc958ff319f4.png)
Por definición, con un único led (On/Off) sólo podemos mostrar dos estados. De la máquina podemos elegir los momentos en dónde se enciende y en dónde se apaga, obviamente son muchísimos.
Además, hay que pensar que esto es cíclico.

**Comment by truelsegaard** [comment]
no están los stage1,2,3,4,Lit?

**Comment by dariosb** [comment]
Si, se pueden utilizar cualquiera de las secuencias definidas en `seqdefs.h`.
@leanfrancucci solo tiene definición de constantes, incluilo tranquilo en los test que lo necesites.
Planteamos la interfaz en `bsp.h` como habíamos dicho pero pasando el código de sequencia:
```
bsp_storageLed(uint seq);
bsp_workStatusLed(uint seq);
```

**Comment by leanfrancucci** [comment]
Los **Led3** y **Led5** son manejados por `CommMgr` y `Collector` respectivamente en el branch https://github.com/vortexmakes/AgroIoT/tree/issue-led-frames-mapping. Resta implementar en `src/bsp.c` las funciones `bsp_storageLed(SeqNo seqNo)` y `bsp_workStatusLed(SeqNo seqNo)`

**Led3** posee 4 estados representados por diferentes secuencias, de acuerdo a los estados de `CommMgr`:
- `SEQ_NO_LIT`: en los estados `Idle` y `Disconnected`. _Red no disponible_
- `SEQ_LSTAGE1`: en el estado `WaitSync`. _Espera para enviar estado actual e historia (60s)_
- `SEQ_LIT`: en el estado `Current`. _Enviando estado actual_
- `SEQ_LSTAGE4`: en el `History`. _Enviando historia_

**Led5** posee 2 estados (por el momento), de acuerdo a los 2 estados disponibles de la región `Mapping` de `Collector`:
- `SEQ_NO_LIT`: en el estado `Stopped`. _No mapea_
- `SEQ_LIT`: en el estado `Running`. _Mapeando_

**Comment by dariosb** [comment]
Implementadas funciones en `src/bsp.c`
Queda pendiente trasladar a algun lugar de acceso rápido el detalle del funcionamiento de los leds
