### ISSUE TITLE
YFrame error

### ISSUE THREAD

**Issue by dariosb** [vortexmakes/AgroIoT#25]
En ciertas ocasiones las llamadas a [YFrame_header ](https://github.com/vortexmakes/AgroIoT/blob/dfa08bf8998366e1f878ecdac9d55df93aacbd7a/src/YFrame/src/YFrame.c#L70) y [YFrame_data ](https://github.com/vortexmakes/AgroIoT/blob/dfa08bf8998366e1f878ecdac9d55df93aacbd7a/src/YFrame/src/YFrame.c#L104) rompen memoria RAM desbordando el stack y entrando en condición de falla fatal al retornar de la función a [Comm_enSendingStatus](https://github.com/vortexmakes/AgroIoT/blob/dfa08bf8998366e1f878ecdac9d55df93aacbd7a/src/CommMgr/src/CommMgrAct.c#L321).
Como primera observación se aprecia cierta vulnerabilidad en sus implementaciones.

La reproducción de la falla es aleatoria y aún no se ha detectado un patrón cierto.
Pero se produce en contexto de la llamada a: [CommMgr_enSendingStatus](https://github.com/vortexmakes/AgroIoT/blob/dfa08bf8998366e1f878ecdac9d55df93aacbd7a/src/CommMgr/src/CommMgrAct.c#L321)
para el envío del estado actual.

![image](https://user-images.githubusercontent.com/4138736/77574139-653cbc00-6eb0-11ea-808b-9c8057cbd232.png)

Con el siguiente contexto en los datos de entrada:
**Name : me->status**
	Details:{position = {utc = "120000", status = "V", latitude = "38.0030396", latInd = "-", longitude = "057.3266218", longInd = "-", speed = "000.000", course = "000", date = "190918"}, devData = {cmd = 0 '\0', m = 0 '\0', h = {hoard = 0, pqty = 0, flow = 0}, a = {x = -8739, y = 0, z = 0, m = 0 '\0'}, hum = 0 '\0'}, ioStatus = {digIn = 255 'ÿ', digOut = 0 '\0'}, batChrStatus = LINE_BATT}

**Name : me->evSendObj.buf**	Details:"!0|18014682004103619,120000,-38.0030396,-057.3266218,000.000,000,190918,00FF,0000,00,00,DDDD,0000,0000,0\0-057.557414,0.031,131,120320,00FE,0000,00,00,FFFF,0000,0000,0|1b,180351,-38.008561,-057.557413,"...

**Comment by leanfrancucci** [comment]
Según verifiqué:
- `me->status` es coherente con `me->evSendObj.buf` "!0|18014682004103619,120000,-38.0030396,-057.3266218,000.000,000,190918,00FF,0000,00,00,DDDD,0000,0000,0"
- Por lo valores de `me->status.position` es una posición inválida
- La longitud de los valores de una posición inválida están de acuerdo con los establecidos en `Geo.h`
- Como todos los campos de tipo String son correctos entonces no hay problema con `strlen()` ni `strcpy()`
- Sin embargo hay variables locales dentro de esas dos funciones y además desde estas se llaman a funciones de otros módulos. Según pude revisar, no habría desborde provocado por estas funciones en las variables locales. Me queda revisar las funciones que son llamadas.
- También podría ser alguna condición que sucede en otro módulo ejecutado en ISR, que coincide en tiempo con la llamada a `CommMgr_enSendingStatus()`

Pregunta, ¿esto ocurre sólo con posición inválida (mientras está arrancando el GPS)?

**Comment by dariosb** [comment]
Pregunta, ¿esto ocurre sólo con posición inválida (mientras está arrancando el GPS)?
No, no siempre, también ha sucedido en varias ocasiones luego de un tiempo prolongado en funcionamiento.
Durante las ultimas pruebas, cambió el comportamiento y se tornó aleatoria la aparición de la falla, siendo imposible hasta ahora forzarla.

**Comment by leanfrancucci** [comment]
Es raro, tal vez algún campo de la posición sobreescribe memoria o algo en ISR. Ya estoy en tema, en cuando lo detectes avisame. De todas maneras, ya estoy trabajando con la verificación de datos desde df, qué como sabemos puede tener problemas

**Comment by leanfrancucci** [comment]
Pregunta, en estas líneas:
https://github.com/vortexmakes/AgroIoT/blob/7d4cf3b2864d4be32bca12ea6f9df7f2e44bca4f/src/geoMgr/geoMgr.c#L293
https://github.com/vortexmakes/AgroIoT/blob/7d4cf3b2864d4be32bca12ea6f9df7f2e44bca4f/src/geoMgr/geoMgr.c#L300

Según el uso de `snprintf()`, ¿el parámetro `size` de `rmcPos2Degrees()` debería ser `LATITUDE_LENGTH + 1` y `LONGITUDE_LENGTH + 1`?

---- Edited
Me parece que está bien con `LATITUDE_LENGTH` y `LONGITUDE_LENGTH`

**Comment by dariosb** [comment]
el tamaño del buffer destino que está en un objeto del tipo Geo, declarado [aca](https://github.com/vortexmakes/AgroIoT/blob/7d4cf3b2864d4be32bca12ea6f9df7f2e44bca4f/src/gps/Geo.h#L51), contempla el '\0'. la llamada a rmcPos2Degress recibe en size el tamaño sin el +1.
En mi opinión está ok

**Comment by dariosb** [comment]
Estoy con una prueba en progreso desde hace un par de horas sin cuelgues.
modifiqué CommMgr_enSendingStatus para que mande una trama cableada:

`static char *buff = "!0|18014682004103619,,,,,,,0000,0000,00,00,0000,0000,0000,0";`

que en lugar de llamar a YFrame hace:
```
memcpy(me->evSendObj.buf, buff, 60);
me->evSendObj.size = 59;
```

Continúo tratando de encontrar algún patrón para poder provocar la condición de falla

**Comment by leanfrancucci** [comment]
Por este tema estoy haciendo estos cambios:
- Agregué protección a la función `YFrame_data()`. Además, permite detectar cuándo alguno de los atributos String no están terminados con '\0'. Esto lo podemos usar con un breakpoint para detectar cuándo ocurre.
- Dejar de utilizar el tipo `GPS_STR`, con lo cual los módulos Collector y CommMgr son más simples, es decir, no se requiere conversión de `GStatus` a `GPS_STR` y viceversa. Y además, en df se almacenan datos binarios no ascii.
- Almacenamiento de datos en df con CRC-32. Estoy desarrollando un mínima abstracción para poder utilizar el módulo de cálculo CRC del STM32

**Comment by dariosb** [comment]
Avisame cuando veas que es factible hacer una prueba de integración corriendo en el target.
Respecto al CRC, estuve probando el módulo y la interfaz es trivial. Definamos una interfaz y preparo el bsp. El Driver de CubeMX da dos maneras de hacer el cálculo CRC32:

```
/**
  * @brief  Computes the 32-bit CRC of 32-bit data buffer using combination
  *         of the previous CRC value and the new one.
  * @param  hcrc pointer to a CRC_HandleTypeDef structure that contains
  *         the configuration information for CRC
  * @param  pBuffer pointer to the buffer containing the data to be computed
  * @param  BufferLength length of the buffer to be computed
  * @retval 32-bit CRC
  */
uint32_t HAL_CRC_Accumulate(CRC_HandleTypeDef *hcrc, uint32_t pBuffer[], uint32_t BufferLength)

/**
  * @brief  Computes the 32-bit CRC of 32-bit data buffer independently
  *         of the previous CRC value.
  * @param  hcrc pointer to a CRC_HandleTypeDef structure that contains
  *         the configuration information for CRC
  * @param  pBuffer Pointer to the buffer containing the data to be computed
  * @param  BufferLength Length of the buffer to be computed
  * @retval 32-bit CRC
  */
uint32_t HAL_CRC_Calculate(CRC_HandleTypeDef *hcrc, uint32_t pBuffer[], uint32_t BufferLength)
```

**Comment by leanfrancucci** [comment]
Acá va la interfaz que está usando agroiot https://github.com/vortexmakes/AgroIoT/blob/issue-25-yfrane-error/src/Crc32/inc/Crc32.h 
Creo que se adapta bien con lo que pasaste de CubeMX

**Comment by dariosb** [comment]
Se corrigieron dos bugs relacionados con un mal manejo de la cola de eventos diferidos en:
- modMgr, no super crítico arrastrado desde el diseño original.
- gsmMgr, se introdujo al introducir las regiones ortogonales. Producía ilegal operation terminando en una falla fatal. Era el origen de la falla reportada al inicio de este issue.
