### ISSUE TITLE
External Power Fail

### ISSUE THREAD

**Issue by dariosb** [vortexmakes/AgroIoT#26]
Al encender, se debe setear las señal PWROFF a 0.
Al detectar ausencia de tensión externa (EXTPOWER = 0), indicar la condición de power fail, manteniendose en funcionamiento con baterías.
Luego que la aplicación cierre las tareas pendientes y asegure la sanidad de las memoria,
decidirá en su propio contexto apagar el equipo.
Al solicitar el apagado del equipo, se acciona PWROFF a 1 y se bloquea toda ejecución posterior.

**Comment by dariosb** [comment]
@leanfrancucci definir quien y como recibe el aviso de PowerFail.
Collector en LIFO evExtPowerFail?

**Comment by leanfrancucci** [comment]
Si lo pensamos para un sistema _cooperative_ el mensaje `evExtPowerFail` debería enviarse al **ao con mayor prioridad** de todo el sistema, y si este procesa más de un mensaje se envía en LIFO. De esta manera siempre estas seguro que no hay ejecución de operaciones contra la df/eeprom en progreso. 

Por el contrario, si el sistema es _preemptive_ tenemos que pensar otra estrategia.

Sin embargo, al ser cooperative el procesamiento de `evExtPowerFail` depende de qué hizo el programador, por ejemplo, agregó una serie de `sleep(5sec)` consecutivos. Para evitar este problema, pensaba en algún mecanismo tipo watchdog, el cual dispara un timer en ISR al detectar power-failure, si `evExtPowerFail` no se procesó para cuando este timer llega a su cuenta final entonces se decreta hacer lo que hace el ao encargado de procesar `evExtPowerFail`.

Por otro lado, ¿qué pasa cuando la energía vuelve antes de procesar `evExtPowerFail`?. Tal vez, al comenzar a procesar este evento, primero prodríamos leer el estado de la señal de power-failure, si se mantiene en falla procedemos, de lo contrario descartamos `evExtPowerFail`.

**Comment by dariosb** [comment]
Actualmente el ao de mayor prioridad es `ModMgr`, por un tema de performance a la hora de procesar el envío/recepción hacia y desde el modulo GSM, lo cual no me parece mal cambiar.
Mas allá de eso,  no me parece que necesariamente tenga que ser el de mayor prioridad ya que hay una batería que aguanta el corte de energía, por lo tanto no habría urgencia extrema.
Si tienen que recibir el `evExtPowerFail `aquel o aquellos ao que acceden a memorias que se pueden corromper por el powerFail, actualmente:
`StatQue      `-> `Collector`
`Config        `->  `ComMgr`? (quien procese los comandos TCP y SMS)
Trace_MSD -> `BSP` debe enterarse, cerrar el archivo actual y desmontar la unidad.

Ademas, si por ejemplo `GsmMgr` se enterase del `evExtPowerFail `podría realizar el normal cierre del socket TCP. **ESTO HAY QUE DESCARTARLO YA QUE EL MODULO NO QUEDA ALIMENTADO CON BATERIAS**

Respecto a la situación en que se halla recuperado la energía durante proceso de apagado, creo que ya que a partir de ese suceso se ejecutarían varias secuencias de cierre, se me ocurre como mejor alternativa que la función que se encarga de accionar la "palanca" de apagado, verifique si hay External Power:
Si ExtPower está presente resetea.
Si ExtPower no está presente acciona el apagado y entra en un bucle que monitorea ExtPower, si vuelve resetea.

**Comment by leanfrancucci** [comment]
Lo que planteas es correcto aunque la idea mía es no confiar en la disponibilidad de batería al menos en lo referido a lo más crítico _los datos en la df_, después de salvarlos, propagamos la señal para que todos los ao hagan lo que crean necesario. 

Manteniendo las prioridades actuales de los ao, entonces existiría un ao nuevo que se encargaría únicamente de salvar los datos ultra-sensibles y además determinaría cuándo apagar o como bien decis reiniciar el equipo. Si decidimos propagar la señal de power-fail vamos a tener que sincronizar este ao con el resto. 

Creo que una entidad independiente que centralice el tema del apagado sería lo más simple y seguro. 

Ni bien termine el tema de la seguridad de los datos arrancamos con esto.

**Comment by leanfrancucci** [comment]
@dariosb  otra cosa que hace falta desarrollar es mantener el estado de la alimentación (lo necesita Collector para enviarlo con cada trama), esto debería estar concentrado en el módulo https://github.com/vortexmakes/AgroIoT/tree/develop/src/BatChr

Recién recuerdo, este módulo ya tiene pensado un tipo de evento para, por ejemplo publicar el power-fail https://github.com/vortexmakes/AgroIoT/blob/7d4cf3b2864d4be32bca12ea6f9df7f2e44bca4f/src/BatChr/BatChr.h#L31

**Comment by dariosb** [comment]
Bien implemento BatChr.
Dado que esta placa no mide el estado de la batería, de las definciones en BatChrStatus, LINE_NOBATT, LINE_BATTCHG, NOLINE_BATTDIS no se van a dar nunca. Realmente no importa creo...
Concentro todo lo relacionado al control de alimentación que ahora está en PwrCtrl en BatChr.

Se usa el tópico Status para propagar el cambio de estado, luego decidimos si posteamos en lifo el powerfail. El formato del evento será evBatChrStatus(state)

**Comment by dariosb** [comment]
@leanfrancucci agrego algunos detalles mas.
En relación la lectura del estado con BatChr_getStatus y yendo al caso real, el equipo no opera con baterías.
La interfaz GSM se cae automáticamente, no tiene alimentación, por lo que no va poder reportar la trama de estado.
Statque va a hacer un flush y no almacena tramas nuevas.
Por lo tanto, en operación normal, en el contexto de las llamadas BatChr_getStatus que pude ver en el código actual, siempre va retornar LINE_BATT.

**Comment by leanfrancucci** [comment]
Si es cierto, entonces `BatChrStatus` quedaría algo así, si mantenemos compatibilidad hacia atrás con el estado de la batería:
```c
enum BatChrStatus
{
    EXT_PWR_OK,
    EXT_PWR_FAIL = 4
};
```
Por otro lado, en power-fail guardamos el estado actual pero con la indicación que hay un power-fail, es decir usamos `EXT_PWR_FAIL`, justamente por eso sería más natural que `BatChr_getStatus()` devuelva `EXT_PWR_FAIL` durante un power-fail. Qué opinás?

**Comment by dariosb** [comment]
Si, me parece bien, lo único que por compatibilidad hacia atrás el indice es 3 no 4
así quedaría mejor:

```
enum BatChrStatus
{
    LINE_BATT,
    EXT_PWR_OK = LINE_BATT,
    NOLINE_BATT = 3,
    EXT_PWR_FAIL = NOLINE_BATT 
};
```

**Comment by leanfrancucci** [comment]
:+1: :+1:

**Comment by leanfrancucci** [comment]
Mañana si queres hacemos un hangout y te cuento qué cambié, como para poder detectar si hay un problema en la df

**Comment by dariosb** [comment]
dale, fijate el último comentario en [issue Yframe Error](https://github.com/vortexmakes/AgroIoT/issues/25#issuecomment-610558022)
