### ISSUE TITLE
Assertion after ffdir_clean

### ISSUE THREAD

**Issue by dariosb** [vortexmakes/AgroIoT#30]
Mientras ConnMgr envía historia, arriba un comando remoto DataFormat por SMS.
Ya que desde que se invoca a ffdir_clean y efectivamente se resetea la ejecución de los AO continúa, ConnMgr pretende continuar con el proceso de envío de historial, lo que provoca que por ejemplo en:
https://github.com/vortexmakes/AgroIoT/blob/68a75abdb1e76e9c865173a40901d5064cd5caca/src/CommMgr/src/CommMgrAct.c#L226-L236
suceda un assertion ya que StatQue quedó empty luego de formatear el directorio.

Lo mencionado arriba respecto a que la ejecución de AO continúa debe ser así dado que luego del parseo y ejecución del comando y antes de resetear, se resuelven el envío de la confirmación del comando hacia el sender y el borrado del mensaje (cuestiones que se realizan utilizando otros AO).

Una opción para corregir el problema que ConnMgr reciba un mensaje en LIFO (o sincronico?) que le informe que el directorio se borró reseteando los atributos que mantienen la cantidad de historial (nFramesToSend)

**Comment by leanfrancucci** [comment]
Ninguno de los AO que acceden a `StatQue` fueron diseñados para soportar formatear a su espalda.
La idea de ejecutar un comando como el del formateo al momento de ser parseado es válido si y sólo si luego de formatear se reinicia el equipo.

Si esto no puede asegurarse, entonces la ejecución de ese comando podría:
1. ser diferida y procesada por un AO diferente al que parsea. `Collector` (como productor) y `CommMgr` (como consumidor) acceden a `StatQue`, hay que revisar si existe otro AO pero creo que no, o
2. realizarse inmediatamente después del parser, luego desactivar los AO que usan `StatQue` y al enviar el ack resetear
3. lo mismo que la anterior pero en lugar de desactivar enviamos un mensaje para que los AO aborten lo que están haciendo

De todas maneras, el hecho que tengamos que seguir funcionando después de ejecutar un comando hasta enviar el ack me parece peligroso hacia el futuro. Prefiero, aplicar un reset después de ejecutar comandos críticos como los de configuración y formateo, es más sano.

Qué opinas?

**Comment by leanfrancucci** [comment]
En qué branch debería aplicar los cambios?

**Comment by dariosb** [comment]
Estoy trabajando sobre el branch issue-YCommand cuando terminemos volvemos a develop te parece?
Respecto a ejecutar el reset inmediatamente después de formatear o de ejecutar cualquiera otro comando, no existe ningún problema de implementación para hacerlo, la cuestión es que se necesita dar una confirmación de la ejecución del comando, (tanto por GPRS o SMS) y eso no se puede hacer en un solo paso del AO.

Por lo que aplicar el reset inmediatamente despues de ejecutar los mandos críticos no lo veo viable. Salvo que encontremos alguna manera de que se pueda apreciar la ejecución del comando de manera remota, por ejemplo:
- Guardar el resultado del comando en memoria y el numero del movil que envió el comando, luego al resetear conociendo la fuente de reset enviar el mensaje de confirmación (SMS).
- Enviar un mensaje cada vez que el equipo inicia, el tema sería definir a que destinatario.... (SMS)
- No encuentro aún una manera de resolverlo por GPRS

Por esto es que creo que la salida está por el lado de poner en contexto a los AO que usan StatQue de que se está en proceso de formateo para que no intenten acceder hasta tanto se complete todo el proceso de confirmación y reinicio.

Qué opinas?

**Comment by leanfrancucci** [comment]
Después de analizar `StatQue` y `ffile` en `Collector` y `CommMgr` y además cada uno de los comandos, empecé a modificar las máquinas de `Collector` y `CommMgr` para que ante el evento `evTerminate` puedan desactivarse por completo. Este evento será generado por la ejecución del comando que lo requiera, por ejemplo para `YCmdDataFormat`:

```c
static RKH_ROM_STATIC_EVENT(evTerminateObj, evTerminate);
...
static rInt 
exec_dataFormat(YCmdParserData *pCmd)
{
    RKH_SMA_POST_LIFO(RKH_UPCAST(collector, &evTerminateObj, ...);
    RKH_SMA_POST_LIFO(RKH_UPCAST(commMgr, &evTerminateObj, ...);
    ffdir_clean();
    pCmd->p->reset = 1;
    return 0;
}
```
Aún el módulo pubsub del fwk no soporta publicación lifo :(
Yo me encargo de modificar `Collector` y `CommMgr` para soportar la desactivación en sus SM.

**Comment by dariosb** [comment]
Ok, agrego los post fifo en YCommand y actualizo los casos de prueba.
