### ISSUE TITLE
Version InvalidFrame

### ISSUE THREAD

**Issue by dariosb** [vortexmakes/AgroIoT#33]
En el viejo si no tenía señal de gps, los campos los llenábamos con valores por defecto y en la fecha metíamos la fecha de liberación del firm, pero cualquier valor que permita rastrearlo en la db sirve, puede ser solo en la trama que viene del reset, o en las no válidas.

**Comment by leanfrancucci** [comment]
Si les parece podemos centralizar la versión de sw (`AGROIOT_VERSION`) y su fecha de liberación (`AGROIOT_RELEASE_DATE`) en un archivo específico, por ejemplo `src/AgroIoTVersion.h`

1. El esquema y semántica del versionado de sw está de acuerdo con [semver](https://semver.org/)
2. `AGROIOT_VERSION` se define como `0xABCCDD`, donde
2.1 `A`: major (1-digit)
2.2 `B`: minor (1-digit)
2.3 `CC`: patch (2-digits)
2.4 `DD`: pre-release (2-digits)
2.5 Ejemplo: 1.2.3 -> `0x120300` --- 1.2.3-beta.1 -> `0x120301`
3. `AGROIOT_RELEASE_DATE` se define como un string con formato `DDMMYY`
4. `AGROIOT_VERSION` y `AGROIOT_RELEASE_DATE` serán incluidas en las tramas de posición inválidas, como así también los traces
5. Las liberaciones se realizarán mediante releases de GitHub, cada release tendrá asociado:
5.1 Un archivo de nombre `agroiot` y formato `tar.gz`, el cual comprime los archivos `AgroIoT.bin`  `AgroIoT.elf`  `symbols.bin`
5.2 Un texto que identifica los cambios de la versión
6. Los releases serán automatizados desde CLI, mediante una serie de scripts

### Ciclo de vida de versiones
#### Pre-release
Un pre-release es una versión, en principio, inestable, que está siendo desarrollada o probada, la cual ha sido publicada por algún motivo. Se identifica con la cadena beta, por ejemplo: x.y.z-beta.n, donde n es el número de versión del pre-release. 
El pre-release x.y.z-beta.1 identifica su primera liberación.
#### Release (versión estable)
Cuando un pre-release se convierte en release, es decir en una versión estable, se elimina el identificador beta y sus versiones. Por ejemplo, si la versión 1.3.0-beta.3 requiere ser liberada, la misma se convertirá en la versión 1.3.0.

**Comment by dariosb** [comment]
Me parece bien, 
una pregunta, la edición de `src/AgroIoTVersion.h` seguiría siendo manual o la automatiza también CLI junto con el build?

Respecto a la generación del archivo `symbols.bin` hoy requiere también de un proceso manual, que en caso de querer automatizarlo habrá que resolver como. Hoy consiste en: 
- descargar el binario AgroIot.elf/bin al **target**
- correr **Trazer** en modo captura desde el puerto al que está conectado el **target**
- poner a correr el **target** hasta al menos el `rkh_fwk_enter,` capturando la publicación de los símbolos.
- finalizar trazer con **ESC**
- renombrar el archivo `instream.bin`, ubicado en el raíz de la instalación de **Trazer**, como symbols.bin

**Comment by leanfrancucci** [comment]
> la edición de src/AgroIoTVersion.h seguiría siendo manual o la automatiza también CLI junto con el build?

Si, es automática.
Respecto de `symbols.bin`, lo veo complejo para la automatización. Tal vez, habría que hacer algo que se genere post-build, por ejemplo, usando el .map. Pero eso es oootro tema

**Comment by dariosb** [comment]
Si, usar el .map lo tenía en mente. El problema es que no todos los simbolos son públicos y por lo tanto no se detallan en el .map
Habría que ver qué se puede hacer, no sé si justifica. Por ahora seguiremos generandolo manualmente.

**Comment by leanfrancucci** [comment]
@truelsegaard @dariosb además de `AGROIOT_VERSION` y `AGROIOT_RELEASE_DATE` qué más podemos agregar en la posición inválida. 
- ¿Algo relacionado con ffile?
- ¿Estadística de las comunicaciones?
- ¿Algo relacionado con los archivos USB o con el mismo USB?
- ...

**Comment by truelsegaard** [comment]
Estaría bueno si se puede poner info del pendrive,si puede quedar registrado en una trama inválida si lo sacan o lo ponen, más que nada para detectar si lo sacan, por si en algún momento faltan datos que nos quede registro del porque...

Les comento brevemente un par de ejemplos que me pasaron que si no los veo no se me hubieran ocurrido, cuando subí a un pulverizador o a una cosechadora a buscar el pendrive para bajar datos ves que el cabeza de termo que lo maneja saco en pendrive para poner un mp3 o para cargar el celular....y lo queres matar...y perdes todo....

**Comment by leanfrancucci** [comment]
> Estaría bueno si se puede poner info del pendrive,si puede quedar registrado en una trama inválida si lo sacan o lo ponen, más que nada para detectar si lo sacan, por si en algún momento faltan datos que nos quede registro del porque...

Podríamos tener un trace para indicar esto y además en las inválidas transmitir el estado de la conexión del pen

**Comment by leanfrancucci** [comment]
Listo, agregado un trace cuando monta (`TraceId_UsbFlashMounted`) y otro cuando desmonta (`TraceId_UsbFlashMounted`), ambos llevan como argumento el estado del módulo `Backup`, `BackupCode` https://github.com/vortexmakes/AgroIoT/blob/5509539297c6bb1763816c2a0da83bc3096a62de/src/Backup/inc/Backup.h#L38

**Comment by leanfrancucci** [comment]
El campo `course` de una posición inválida lleva el estado del módulo `Backup`, `BackupCode` https://github.com/vortexmakes/AgroIoT/blob/5509539297c6bb1763816c2a0da83bc3096a62de/src/Backup/inc/Backup.h#L38
